---
# File to sen src files to Pi
# You need to copy your ssh keys to the pi in order for this to work
# ansible-playbook -i inventories/hosts -u pi deploy.yml
- hosts: pis
  become: yes
  gather_facts: false

  tasks:
      - name: copy ../src for testing
        copy:
            src: ../src
            dest: /home/pi

      - name: make the ~/src/flask-stream-example directory
        file:
          path: /home/pi/src/flask-stream-example
          state: directory
          mode: 0777

      - name: Copy site files to /var/www/pi-baby-monitor
        copy:
            src: ../src/public_html
            dest: /var/www/pi-baby-monitor

      - name: Install flask video streaming repo
        git:
          repo: 'https://github.com/miguelgrinberg/flask-video-streaming'
          dest: /home/pi/src/flask-stream-example
          clone: yes

  # post_tasks:
  #     - name: reboot PIs
  #       reboot:
